#!/usr/bin/env python3
"""Extract PROGMEM frames from OLED Animation Maker .ino files."""

import re
import sys
from pathlib import Path

CLIPS = [
    ("idle_blink", "oled_display (3).ino", "OledFaceIdleBlink", 12, 125),
    ("look_lr", "oled_display.ino", "OledFaceLookLR", 8, 250),
    ("alert", "oled_display (1).ino", "OledFaceAlert", 16, 125),
    ("happy", "oled_display (2).ino", "OledFaceHappy", 20, 100),
]

DOWNLOADS = Path(r"C:\Users\oscar\Downloads")
OUT_DIR = Path(__file__).resolve().parent.parent / "src" / "oled_faces"
OUT_CPP = OUT_DIR / "oled_face_data.cpp"
OUT_H = Path(__file__).resolve().parent.parent / "src" / "oled_face_clip.h"

FRAME_RE = re.compile(
    r"const uint8_t PROGMEM (frame\d+)\[1024\] = \{([^}]+)\};",
    re.DOTALL,
)


def extract_frames(text: str) -> list[tuple[str, str]]:
    frames = []
    for m in FRAME_RE.finditer(text):
        body = m.group(2).strip()
        frames.append((m.group(1), body))
    return frames


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    cpp_lines = [
        "// Auto-generated by tools/import_oled_faces.py — ~56 KB PROGMEM total.",
        '#include "oled_face_clip.h"',
        "#include <avr/pgmspace.h>",
        "",
    ]

    clip_meta: list[tuple[str, str, int, int]] = []

    for slug, ino_name, prefix, expect_count, interval in CLIPS:
        ino_path = DOWNLOADS / ino_name
        if not ino_path.exists():
            print(f"Missing {ino_path}", file=sys.stderr)
            return 1
        text = ino_path.read_text(encoding="utf-8", errors="replace")
        frames = extract_frames(text)
        if len(frames) != expect_count:
            print(f"{ino_name}: expected {expect_count} frames, got {len(frames)}", file=sys.stderr)
            return 1

        frame_names = []
        for i, (_, body) in enumerate(frames):
            name = f"k{prefix}Frame{i}"
            frame_names.append(name)
            cpp_lines.append(f"const uint8_t PROGMEM {name}[1024] = {{")
            cpp_lines.append(f"  {body}")
            cpp_lines.append("};")
            cpp_lines.append("")

        array_name = f"k{prefix}Frames"
        cpp_lines.append(f"const uint8_t* const PROGMEM {array_name}[] = {{")
        cpp_lines.extend(f"  {n}," for n in frame_names)
        cpp_lines.append("};")
        cpp_lines.append("")
        clip_meta.append((prefix, array_name, expect_count, interval))

    OUT_CPP.write_text("\n".join(cpp_lines), encoding="utf-8")

    h_lines = [
        "// OLED face clip player — metadata + frame advance (Arduino-free).",
        "#ifndef OLED_FACE_CLIP_H",
        "#define OLED_FACE_CLIP_H",
        "",
        "#include <cstdint>",
        "",
        "enum class OledFaceClipId : uint8_t {",
        "    IdleBlink = 0,",
        "    LookLR,",
        "    Alert,",
        "    Happy,",
        "};",
        "",
        '#include "pesto_emotion.h"',
        '#include "sense_mood.h"',
        "",
        "struct OledFaceClipMeta {",
        "    uint8_t frameCount;",
        "    uint16_t frameIntervalMs;",
        "};",
        "",
        "inline OledFaceClipMeta oledFaceClipMeta(OledFaceClipId id) {",
        "    switch (id) {",
    ]

    meta_map = {
        "OledFaceIdleBlink": clip_meta[0],
        "OledFaceLookLR": clip_meta[1],
        "OledFaceAlert": clip_meta[2],
        "OledFaceHappy": clip_meta[3],
    }
    for clip_id in ["IdleBlink", "LookLR", "Alert", "Happy"]:
        prefix = f"OledFace{clip_id}"
        _, _, count, interval = meta_map[f"OledFace{clip_id}"]
        h_lines.append(f"        case OledFaceClipId::{clip_id}:")
        h_lines.append(f"            return OledFaceClipMeta{{{count}, {interval}}};")

    h_lines.extend([
        "        default:",
        "            return OledFaceClipMeta{1, 125};",
        "    }",
        "}",
        "",
        "inline uint8_t oledFaceAdvanceFrame(OledFaceClipId clip, uint8_t frameIdx, uint32_t now,",
        "        uint32_t lastMs) {",
        "    const OledFaceClipMeta meta = oledFaceClipMeta(clip);",
        "    if (meta.frameCount == 0) {",
        "        return 0;",
        "    }",
        "    if (lastMs == 0 || (now - lastMs) >= meta.frameIntervalMs) {",
        "        return (uint8_t)((frameIdx + 1) % meta.frameCount);",
        "    }",
        "    return frameIdx;",
        "}",
        "",
        "inline OledFaceClipId oledFaceForSense(PestoEmotion emotion, SenseTrigger trigger, bool seeking) {",
        "    (void)emotion;",
        "    if (trigger == SenseTrigger::Distance || trigger == SenseTrigger::Gyro) {",
        "        return OledFaceClipId::Alert;",
        "    }",
        "    if (trigger == SenseTrigger::Mic || trigger == SenseTrigger::Light) {",
        "        if (emotion == PestoEmotion::LookLeft || emotion == PestoEmotion::LookRight) {",
        "            return OledFaceClipId::LookLR;",
        "        }",
        "        return OledFaceClipId::Happy;",
        "    }",
        "    if (seeking) {",
        "        return OledFaceClipId::Happy;",
        "    }",
        "    return OledFaceClipId::IdleBlink;",
        "}",
        "",
        "#ifdef ARDUINO",
        "#include <Arduino.h>",
        "const uint8_t* oledFaceFrameData(OledFaceClipId id, uint8_t frameIdx);",
        "#endif",
        "",
        "#endif // OLED_FACE_CLIP_H",
    ])

    h_lines.insert(10, "")
    # includes added after enum in header template above

    OUT_H.write_text("\n".join(h_lines), encoding="utf-8")

    # Append Arduino frame accessor to cpp
    accessor = [
        "",
        "const uint8_t* oledFaceFrameData(OledFaceClipId id, uint8_t frameIdx) {",
        "    switch (id) {",
    ]
    for prefix, array_name, count, _ in clip_meta:
        clip_enum = prefix.replace("OledFace", "")
        accessor.append(f"        case OledFaceClipId::{clip_enum}:")
        accessor.append(f"            if (frameIdx >= {count}) frameIdx = 0;")
        accessor.append(
            f"            return (const uint8_t*)pgm_read_ptr(&{array_name}[frameIdx]);"
        )
    accessor.extend([
        "        default:",
        "            return kOledFaceIdleBlinkFrame0;",
        "    }",
        "}",
    ])
    with OUT_CPP.open("a", encoding="utf-8") as f:
        f.write("\n".join(accessor))

    print(f"Wrote {OUT_CPP} and {OUT_H}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
